name: Doxygen

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron:  '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: dealii/dealii:master-focal
      options: --user root

    steps:
      - name: Setup
        run: |
          apt-get update
          apt-get install -y doxygen graphviz

      - uses: actions/checkout@v2
      
      - name: Compile
        run: |
          mkdir build
          cd build
          cmake ../ -DCMAKE_BUILD_TYPE=Release
          make doxygen

      - name: Test
        run: |
          cd build/doc/doxygen
          if [ ! -f doxygen.out ]; then echo "No Doxygen output file found!"; exit 1; else echo "Doxygen finished with the following output:"; cat doxygen.out; fi
          if [ ! -f doxygen.err ]; then echo "No Doxygen error file found!"; exit 1; fi
          if [ -s doxygen.err ]; then echo "Doxygen failed with the following error(s):"; cat doxygen.err; exit 1; else echo "Doxygen passed."; fi

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: doxygen
          path: ./build/doc/doxygen/html

  deploy:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: doxygen
          path: ./build/doc/doxygen/html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY_DOXYGEN }}
          external_repository: PartExa/PartExa-Doxygen
          publish_branch: master
          publish_dir: ./build/doc/doxygen/html
